ALTER TABLE "Offer" ADD COLUMN "errorMessage" TEXT;
ALTER TABLE "Offer" ADD COLUMN "retryCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Offer" ADD COLUMN "lastAttemptAt" DATETIME;
ALTER TABLE "Offer" ADD COLUMN "source" TEXT;
